---
- name: Database Installation
  hosts: client
  become: yes
  become_user: root
  tasks:
  - name: Install Mysql
    apt:
      name: mysql-server
  - name: Start mysql server
    service:
      name: mysql
      state: started
      enabled: true      
  - name: Install mongodb
    apt:
      name: mongodb
      state: latest
  - name: Start mongodb service
    service:
      name: mongodb
      state: started
  - name: Install redis server
    apt:
      name: redis-server
      state: latest
  - name: Install cassandra
    command: echo "deb https://downloads.apache.org/cassandra/debian 40x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - name: Install curl
    apt:
      name: apt-transport-https
  - name: Install cassandra1
    shell: |
      sh -c 'echo "deb http://www.apache.org/dist/cassandra/debian 40x main" > /etc/apt/sources.list.d/cassandra.list'
  - name: Wget cassandra
    shell: |
      wget -q -O - https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
  - name: Wget elastisearch
    shell: |
      wget -q -O - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - name: Install elstic
    shell: |
      echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
  - name: Installation
    apt:
      name: cassandra
      state: present
      update_cache: yes
  - name: Elastisearch
    apt:
      name: elasticsearch
      state: latest
      update_cache: yes



